/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as ReferralsRouteImport } from './routes/referrals'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LobbyRouteImport } from './routes/lobby'
import { Route as ChartsRouteImport } from './routes/charts'
import { Route as AntiCheatRouteImport } from './routes/anti-cheat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MatchIdRouteImport } from './routes/match.$id'
import { Route as GamesSlugRouteImport } from './routes/games.$slug'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralsRoute = ReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LobbyRoute = LobbyRouteImport.update({
  id: '/lobby',
  path: '/lobby',
  getParentRoute: () => rootRouteImport,
} as any)
const ChartsRoute = ChartsRouteImport.update({
  id: '/charts',
  path: '/charts',
  getParentRoute: () => rootRouteImport,
} as any)
const AntiCheatRoute = AntiCheatRouteImport.update({
  id: '/anti-cheat',
  path: '/anti-cheat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchIdRoute = MatchIdRouteImport.update({
  id: '/match/$id',
  path: '/match/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesSlugRoute = GamesSlugRouteImport.update({
  id: '/games/$slug',
  path: '/games/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anti-cheat': typeof AntiCheatRoute
  '/charts': typeof ChartsRoute
  '/lobby': typeof LobbyRoute
  '/profile': typeof ProfileRoute
  '/referrals': typeof ReferralsRoute
  '/wallet': typeof WalletRoute
  '/games/$slug': typeof GamesSlugRoute
  '/match/$id': typeof MatchIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anti-cheat': typeof AntiCheatRoute
  '/charts': typeof ChartsRoute
  '/lobby': typeof LobbyRoute
  '/profile': typeof ProfileRoute
  '/referrals': typeof ReferralsRoute
  '/wallet': typeof WalletRoute
  '/games/$slug': typeof GamesSlugRoute
  '/match/$id': typeof MatchIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anti-cheat': typeof AntiCheatRoute
  '/charts': typeof ChartsRoute
  '/lobby': typeof LobbyRoute
  '/profile': typeof ProfileRoute
  '/referrals': typeof ReferralsRoute
  '/wallet': typeof WalletRoute
  '/games/$slug': typeof GamesSlugRoute
  '/match/$id': typeof MatchIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anti-cheat'
    | '/charts'
    | '/lobby'
    | '/profile'
    | '/referrals'
    | '/wallet'
    | '/games/$slug'
    | '/match/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anti-cheat'
    | '/charts'
    | '/lobby'
    | '/profile'
    | '/referrals'
    | '/wallet'
    | '/games/$slug'
    | '/match/$id'
  id:
    | '__root__'
    | '/'
    | '/anti-cheat'
    | '/charts'
    | '/lobby'
    | '/profile'
    | '/referrals'
    | '/wallet'
    | '/games/$slug'
    | '/match/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AntiCheatRoute: typeof AntiCheatRoute
  ChartsRoute: typeof ChartsRoute
  LobbyRoute: typeof LobbyRoute
  ProfileRoute: typeof ProfileRoute
  ReferralsRoute: typeof ReferralsRoute
  WalletRoute: typeof WalletRoute
  GamesSlugRoute: typeof GamesSlugRoute
  MatchIdRoute: typeof MatchIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referrals': {
      id: '/referrals'
      path: '/referrals'
      fullPath: '/referrals'
      preLoaderRoute: typeof ReferralsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lobby': {
      id: '/lobby'
      path: '/lobby'
      fullPath: '/lobby'
      preLoaderRoute: typeof LobbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charts': {
      id: '/charts'
      path: '/charts'
      fullPath: '/charts'
      preLoaderRoute: typeof ChartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anti-cheat': {
      id: '/anti-cheat'
      path: '/anti-cheat'
      fullPath: '/anti-cheat'
      preLoaderRoute: typeof AntiCheatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match/$id': {
      id: '/match/$id'
      path: '/match/$id'
      fullPath: '/match/$id'
      preLoaderRoute: typeof MatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$slug': {
      id: '/games/$slug'
      path: '/games/$slug'
      fullPath: '/games/$slug'
      preLoaderRoute: typeof GamesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AntiCheatRoute: AntiCheatRoute,
  ChartsRoute: ChartsRoute,
  LobbyRoute: LobbyRoute,
  ProfileRoute: ProfileRoute,
  ReferralsRoute: ReferralsRoute,
  WalletRoute: WalletRoute,
  GamesSlugRoute: GamesSlugRoute,
  MatchIdRoute: MatchIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
